# Generated by Django 4.2.2 on 2023-07-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(default='default/icon.png', upload_to='user/'),
        ),
    ]
